import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/provider/AuthProvider";
import {Toaster} from "react-hot-toast"
import Layout from "@/component/Layout"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Necxis",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      style={
        {
          "--font-geist-sans": geistSans.variable,
          "--font-geist-mono": geistMono.variable,
        } as React.CSSProperties
      }
    >
      <body className="antialiased">
        <Toaster position="top-center"/> 
          <AuthProvider>
            <Layout>
              {children}
            </Layout>
          </AuthProvider>
        
      </body>
    </html>
  );
}